import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { CatsProvider } from "@/hooks/CatsProvider";
import {
  WalletConnectProvider,
} from "@/hooks/WalletConnectProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Crowder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CatsProvider>
          <WalletConnectProvider>{children}</WalletConnectProvider>
        </CatsProvider>
      </body>
    </html>
  );
}
